(write-line "Enter a number:")
(setq n (read))
(setq bl 1)
(cond ((< n 2)
(setq bl 0)))
;(terpri) ; Used for line breaks，similar to '\n' in C.
(cond ((= n 2)
(setq bl 1)))
(cond ((> n 2)
(loop for x from 2 to (- n 1)
do (write-line " " ) ; The syntax error without this line.
(if(= 0 (mod n x) )
(setq bl 0)
)
)
))
(if (= 1 bl)
(format t "~%The number ~d is a prime." n)
)
(if (= 0 bl)
(format t "~%The number ~d is NOT a prime." n)
)
